application: echo-sense
version: 0-62
runtime: python27
api_version: 1
threadsafe: true
instance_class: B2
default_expiration: "99d"

inbound_services:
- warmup

basic_scaling:
  max_instances: 35
  idle_timeout: 10m

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /favicons
  static_dir: static/favicons

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /tasks/
  script: echosense.app
  login: admin

- url: /dist/src
  static_dir: dist/src

- url: /dist/build
  static_dir: dist/build

- url: /admin/gauth.*
  script: echosense.app
  login: admin
  secure: always

- url: /docs
  static_dir: docs/_build/html

- url: /.*
  script: echosense.app

builtins:
- deferred: on
- remote_api: on


libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: ssl
  version: "latest"
- name: numpy
  version: "latest"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.woff2$
- ^(.*/)?.*\.db$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
